### ISSUE TITLE
[DB] Populate Script

### ISSUE THREAD

**Issue by freemanpivo** [kanneta/ProjeteOn-api#2]
Populate the Database with some mocks to test the application.

**Comment by kaiqueborges** [comment]
Segue o link [https://app.sqldbm.com/MySQL/Share/AfxtFuiiGk4JPwo2i44iUkGFrngIE8md_DYjF4jNYw0](url).

Lembrando que fiz na pressa, fique à vontade para renomaer as coisas

**Comment by freemanpivo** [comment]
Presta atenção na aula, pô!

**Comment by freemanpivo** [comment]
@kaiqueborges o link não tá abrindo!

**Comment by freemanpivo** [comment]
@kaiqueborges, 
habilita o ZenHub na organização, fica mais fácil gerenciar as issues.
